name: CI

on:
  push:
    branches: [main]

jobs:

  saludar2:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar el código
        uses: actions/checkout@v5

      - name: Ejecutar mi script
        run: ./scripts/hola.sh Pipeline

      - name: Mostrar info del runner
        run: |
          echo "Sistema: $(uname -a)"
          echo "Usuario: $(whoami)"
          ls -la

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar el código
        uses: actions/checkout@v5

      - name: Compilar
        run: |
          echo "Empaquetando la app..."
          echo "build del $(date +%F)" > app.txt
          cat app.txt

  test:
    runs-on: ubuntu-latest
    needs: build,saludar2
    steps:
      - name: Bajar el código
        uses: actions/checkout@v5

      - name: Correr tests
        run: |
          echo "Corriendo tests..."
          ./scripts/hola.sh Test

  seguridad:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Escanear
        run: echo "Buscando vulnerabilidades... todo OK ✅"

  deploy:
    runs-on: ubuntu-latest
    needs: [test, seguridad]
    environment: produccion
    steps:
      - name: Desplegar
        run: echo "Poniendo en producción 🚀"

  
